# Site settings
title: Donghyuk Shin
email: dshin@kaist.ac.kr
description: # Website of Dr. Donghyuk Shin
baseurl: # the subpath of your site, e.g. /blog/
url: https://dshin32.github.io # the base hostname & protocol for your site

# Google analytics ID: Uncomment and your own, if you like
google_analytics: UA-96121815-1
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
    Donghyuk Shin<br/>
    Assistant Professor<br/>
    Dept. of Information Systems<br/>
    W. P. Carey School of Business<br/>
    Arizona State University

location: >
  Dept. of Information Systems<br/>
  W. P. Carey School of Business<br/>
  PO Box 874606<br/>
  Tempe, AZ 85287-4606

contact: >
    <i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;dhs -at- asu -dot- edu<br/>
    <i class="fa fa-university" aria-hidden="true"></i>&nbsp;&nbsp;BAC 652<br/>
    &nbsp;<i class="fa fa-phone" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;602 496 1026
# <a href="mailto:dhs@asu.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact via email</a> <br/>
# <a href="https://github.com/sbryngelson/academic-website-template"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  # - name: about
  - name: publications
  # - name: talks
  # - name: research
  # - name: software
  # - name: team
  - name: teaching
  # - name: other

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Shin
  first_name: [Donghyuk]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
